version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @angular/cli@18.0.2
  pre_build:
    commands:
      - npm install
      - npm install -g @angular/cli@18.0.2
  build:
    commands:
      - ng build --prod
artifacts:
  files:
    - '**/*'

